# This file was generated by GoReleaser. DO NOT EDIT.
class Posync < Formula
  desc "Upload pot and download mo files from poeditor.com"
  homepage "https://github.com/frozzare/posync"
  url "https://github.com/frozzare/posync/releases/download/v2.0.0/posync_2.0.0_darwin_amd64.tar.gz"
  version "2.0.0"
  sha256 "82013b2827b431f29342ba4fa11cd5f610b47c1a19409e9e420175ec2af880ef"

  def install
    bin.install "posync"
  end

  test do
    system "#{bin}/posync --version"
  end
end
